// Generated by CoffeeScript 1.8.0
(function() {
  var bcrypt;

  bcrypt = require('bcrypt');

  module.exports = {

    /*
    	 * @param {String} username 用户名
    	 * @param {String} password 密码
     */
    login: function(req, res) {
      var password, username;
      username = req.body.username;
      password = req.body.password;
      return async.waterfall([
        function(cb) {
          if (username == null) {
            return cb('参数username不能为空');
          }
          if (password == null) {
            return cb('参数password不能为空');
          }
          return cb(null);
        }, function(cb) {
          return User.findOne({
            username: username
          }).exec(function(err, user) {
            if (err != null) {
              return cb(err);
            }
            if (user == null) {
              return cb('用户名不存在');
            }
            return cb(null, user);
          });
        }, function(user, cb) {
          return bcrypt.compare(password, user.password, function(err, match) {
            if (err != null) {
              return cb(err);
            }
            if (!match) {
              return cb('用户密码错误');
            } else {
              return cb(null, user);
            }
          });
        }
      ], function(err, user) {
        if (err) {
          return res.status(400).send(err);
        }
        req.session.authenticated = true;
        req.session.username = user.username;
        return res.status(200).json(user);
      });
    },
    logout: function(req, res) {
      req.session.destroy();
      return res.json({
        status: true,
        result: '登出成功'
      });
    }
  };

}).call(this);
