// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    attributes: {
      content: {
        type: 'string',
        required: true
      },
      toJSON: function() {
        var obj;
        obj = this.toObject();
        delete obj.content;
        delete obj.createdAt;
        return obj.updatedAt;
      }
    }
  };

}).call(this);
